In [3]:
import numpy as np
import tensorflow as tf
import keras
import keras.backend as k


from keras.optimizers import SGD,Adam,Adagrad, RMSprop
from keras.applications import *
from keras.preprocessing import *
from tensorflow.keras.utils import img_to_array,array_to_img
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.models import Sequential
from keras.layers import Dense,Conv2D, MaxPool2D, Flatten,Activation,BatchNormalization,Dropout
from keras.utils.np_utils import to_categorical
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as pool_size
import glob
from PIL import Image
import os
from os import listdir

In [4]:
dirName = '/content/drive/MyDrive/Digital Naturalist/Augument Dataset'
folders = listdir(dirName)
def getListOfFiles(dirName):
  listOfFile = os.listdir(dirName)
  allFiles = list()
  for fol_name in listOfFile:
    fullPath = os.path.join(dirName, fol_name)
    allFiles.append(fullPath)
  return allFiles
Folders = getListOfFiles(dirName)
len(Folders)
subfolders = []
for num in range(len(Folders)):
  sub_fols = getListOfFiles(Folders[num])
  subfolders+=sub_fols
subfolders

['/content/drive/MyDrive/Digital Naturalist/Augument Dataset/GIB_AUG/aug_download (1)_0_8130.jpg',
 '/content/drive/MyDrive/Digital Naturalist/Augument Dataset/GIB_AUG/aug_download (1)_0_5189.jpg',
 '/content/drive/MyDrive/Digital Naturalist/Augument Dataset/GIB_AUG/aug_download (1)_0_6484.jpg',
 '/content/drive/MyDrive/Digital Naturalist/Augument Dataset/GIB_AUG/aug_download (1)_0_2186.jpg',
 '/content/drive/MyDrive/Digital Naturalist/Augument Dataset/GIB_AUG/aug_download (1)_0_412.jpg',
 '/content/drive/MyDrive/Digital Naturalist/Augument Dataset/GIB_AUG/aug_download (1)_0_8763.jpg',
 '/content/drive/MyDrive/Digital Naturalist/Augument Dataset/GIB_AUG/aug_download (1)_0_5696.jpg',
 '/content/drive/MyDrive/Digital Naturalist/Augument Dataset/GIB_AUG/aug_download (1)_0_2994.jpg',
 '/content/drive/MyDrive/Digital Naturalist/Augument Dataset/GIB_AUG/aug_download (1)_0_8712.jpg',
 '/content/drive/MyDrive/Digital Naturalist/Augument Dataset/GIB_AUG/aug_download (1)_0_9193.jpg',
 '/content/

In [5]:
X_data = [0,1,2,3,4,5]
Y_data = [0,1,2,3,4,5]
id_no=0
found=[]
for paths in subfolders:
  files = glob.glob (paths+"/*.jpg")
  found.append((paths.split(os.sep)[-2],paths.split(os.sep)[-1]))
  for myFile in files:
    img = Image.open(myFile)
    img = img.resize((224,224),Image.ANTIALIAS)
    img = np.array(img)
    if img.shape == (224,224,3):
      X_data.append(img)
      Y_data.append(id_no)
  id_no+=1

In [6]:
print(X_data)
print(Y_data)
X= np.array(X_data)
Y = np.array(Y_data)
print("x-shape",X.shape, "y shape", Y.shape)
X=X.astype('float32')/255.0
y_cat = to_categorical(Y_data, len(subfolders)) 
print("X shape",X, "y_cat shape", y_cat) 
print("X shape",X.shape, "y_cat shape", y_cat.shape)
X_train, X_test, y_train, y_test = train_test_split(X, y_cat, test_size=0.2)
print("The model has " + str(len(X_train)) + " inputs")
print("The model has " + str(len(X_test)) + " inputs")

[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5]
x-shape (6,) y shape (6,)
X shape [0.         0.00392157 0.00784314 0.01176471 0.01568628 0.01960784] y_cat shape [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
X shape (6,) y_cat shape (6, 2916)
The model has 4 inputs
The model has 2 inputs


In [7]:
save_to_dir='/content/drive/MyDrive/Digital Naturalist/testset'